[package]
name = "service"
version = "0.1.0"
authors = ["Richard <qpotizo@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
tokio = { version = "0.2", features = ["full"] }
zerocopy = "0.3.0"
byteorder = "1.3.4"
